USE [master]
GO
/****** Object:  Database [userLogin]    Script Date: 10/25/2020 7:10:38 PM ******/
CREATE DATABASE [userLogin]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'userLogin', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\userLogin.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'userLogin_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\userLogin_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [userLogin] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [userLogin].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [userLogin] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [userLogin] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [userLogin] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [userLogin] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [userLogin] SET ARITHABORT OFF 
GO
ALTER DATABASE [userLogin] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [userLogin] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [userLogin] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [userLogin] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [userLogin] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [userLogin] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [userLogin] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [userLogin] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [userLogin] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [userLogin] SET  DISABLE_BROKER 
GO
ALTER DATABASE [userLogin] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [userLogin] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [userLogin] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [userLogin] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [userLogin] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [userLogin] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [userLogin] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [userLogin] SET RECOVERY FULL 
GO
ALTER DATABASE [userLogin] SET  MULTI_USER 
GO
ALTER DATABASE [userLogin] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [userLogin] SET DB_CHAINING OFF 
GO
ALTER DATABASE [userLogin] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [userLogin] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [userLogin] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'userLogin', N'ON'
GO
ALTER DATABASE [userLogin] SET QUERY_STORE = OFF
GO
USE [userLogin]
GO
/****** Object:  Table [dbo].[Logins]    Script Date: 10/25/2020 7:10:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Logins](
	[Id] [int] NOT NULL,
	[LoginId] [int] NULL,
	[UserName] [nvarchar](100) NULL,
	[Password] [nvarchar](100) NULL,
 CONSTRAINT [PK_Logins] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[Logins] ([Id], [LoginId], [UserName], [Password]) VALUES (1, 1, N'admin', N'admin')
GO
INSERT [dbo].[Logins] ([Id], [LoginId], [UserName], [Password]) VALUES (2, 1, N'sys', N'sys')
GO
USE [master]
GO
ALTER DATABASE [userLogin] SET  READ_WRITE 
GO
